name: Trivy Security Scan

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:
    inputs: {}

jobs:
  security-scan:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Security Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # just scan the latest released image
          image-ref: 'ghcr.io/prashant-shahi/k8s-wait-for:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Fail if scan found vulnerabilities
        run: |
          grep -q '"rules": \[],' trivy-results.sarif
